digite: str = input("Digite algo ")
print("O tipo primitivo deste texto é {}".format(type(digite)))
print("Só tem espaços? ", digite.isspace())
print("É um númeo? ", digite.isnumeric())
print("É alfabético? ", digite.isalpha())
print("É Alfanumérico ", digite.isalnum())
print("Está em maiúsculas? ", digite.isupper())
print("Está em minúsculas? ", digite.islower())
print("Está capitalizada? ", digite.istitle())
